<?xml version="1.0"?>
<package format="3">
  <name>motor_rex_task_planner</name>
  <version>0.1.0</version>
  <description>Task planner for simulated robotic electric motor recovery.</description>
  <maintainer email="demo@example.com">Dubai Motor Re-X Team</maintainer>
  <license>MIT</license>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>motor_rex_decision_engine</exec_depend>
  <exec_depend>motor_rex_gazebo</exec_depend>
  <exec_depend>motor_rex_moveit_config</exec_depend>
  <exec_depend>motor_rex_perception_mock</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
